=== luboid/leontestbed/bc2/sample/Schema/camt.009.001.04.xsd
<?xml version="1.0" encoding="UTF-8"?><!--Generated by SWIFTStandards Workstation (build:R7.0.2.1) on 2009 Jul 01 10:55:47--><xs:schema xmlns="urn:swift:xsd:camt.009.001.04" xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" targetNamespace="urn:swift:xsd:camt.009.001.04">
    <xs:element name="Document" type="Document"/>
    <xs:complexType name="AccountIdentification1Choice">
        <xs:sequence>
            <xs:choice>
                <xs:element name="IBAN" type="IBANIdentifier"/>
                <xs:element name="BBAN" type="BBANIdentifier"/>
                <xs:element name="UPIC" type="UPICIdentifier"/>
                <xs:element name="DmstAcct" type="SimpleIdentificationInformation"/>
            </xs:choice>
        </xs:sequence>
    </xs:complexType>
    <xs:simpleType name="AustrianBankleitzahlIdentifier">
        <xs:restriction base="xs:string">
            <xs:pattern value="AT[0-9]{5,5}"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="BBANIdentifier">
        <xs:restriction base="xs:string">
            <xs:pattern value="[a-zA-Z0-9]{1,30}"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="BICIdentifier">
        <xs:restriction base="xs:string">
            <xs:pattern value="[A-Z]{6,6}[A-Z2-9][A-NP-Z0-9]([A-Z0-9]{3,3}){0,1}"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="CHIPSParticipantIdentifier">
        <xs:restriction base="xs:string">
            <xs:pattern value="CP[0-9]{4,4}"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="CHIPSUniversalIdentifier">
        <xs:restriction base="xs:string">
            <xs:pattern value="CH[0-9]{6,6}"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="CanadianPaymentsARNIdentifier">
        <xs:restriction base="xs:string">
            <xs:pattern value="CA[0-9]{9,9}"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="CashClearingSystem1Code">
        <xs:restriction base="xs:string">
            <xs:enumeration value="ABE"/>
            <xs:enumeration value="ART"/>
            <xs:enumeration value="AVP"/>
            <xs:enumeration value="AZM"/>
            <xs:enumeration value="BAP"/>
            <xs:enumeration value="BEL"/>
            <xs:enumeration value="BOF"/>
            <xs:enumeration value="BRL"/>
            <xs:enumeration value="CAD"/>
            <xs:enumeration value="CAM"/>
            <xs:enumeration value="CBJ"/>
            <xs:enumeration value="CHP"/>
            <xs:enumeration value="DKC"/>
            <xs:enumeration value="RTP"/>
            <xs:enumeration value="EBA"/>
            <xs:enumeration value="ELS"/>
            <xs:enumeration value="ERP"/>
            <xs:enumeration value="XCT"/>
            <xs:enumeration value="HRK"/>
            <xs:enumeration value="HRM"/>
            <xs:enumeration value="HUF"/>
            <xs:enumeration value="LGS"/>
            <xs:enumeration value="LVL"/>
            <xs:enumeration value="MOS"/>
            <xs:enumeration value="MUP"/>
            <xs:enumeration value="NOC"/>
            <xs:enumeration value="PCH"/>
            <xs:enumeration value="PDS"/>
            <xs:enumeration value="PEG"/>
            <xs:enumeration value="PNS"/>
            <xs:enumeration value="PVE"/>
            <xs:enumeration value="SEC"/>
            <xs:enumeration value="SIT"/>
            <xs:enumeration value="SLB"/>
            <xs:enumeration value="SPG"/>
            <xs:enumeration value="SSK"/>
            <xs:enumeration value="TBF"/>
            <xs:enumeration value="TGT"/>
            <xs:enumeration value="TOP"/>
            <xs:enumeration value="FDW"/>
            <xs:enumeration value="BOJ"/>
            <xs:enumeration value="FEY"/>
            <xs:enumeration value="ZEN"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:complexType name="ClearingSystemMemberIdentificationChoice">
        <xs:sequence>
            <xs:choice>
                <xs:element name="USCHU" type="CHIPSUniversalIdentifier"/>
                <xs:element name="NZNCC" type="NewZealandNCCIdentifier"/>
                <xs:element name="IENSC" type="IrishNSCIdentifier"/>
                <xs:element name="GBSC" type="UKDomesticSortCodeIdentifier"/>
                <xs:element name="USCH" type="CHIPSParticipantIdentifier"/>
                <xs:element name="CHBC" type="SwissBCIdentifier"/>
                <xs:element name="USFW" type="FedwireRoutingNumberIdentifier"/>
                <xs:element name="PTNCC" type="PortugueseNCCIdentifier"/>
                <xs:element name="RUCB" type="RussianCentralBankIdentificationCodeIdentifier"/>
                <xs:element name="ITNCC" type="ItalianDomesticIdentifier"/>
                <xs:element name="ATBLZ" type="AustrianBankleitzahlIdentifier"/>
                <xs:element name="CACPA" type="CanadianPaymentsARNIdentifier"/>
                <xs:element name="CHSIC" type="SwissSICIdentifier"/>
                <xs:element name="DEBLZ" type="GermanBankleitzahlIdentifier"/>
                <xs:element name="ESNCC" type="SpanishDomesticInterbankingIdentifier"/>
                <xs:element name="ZANCC" type="SouthAfricanNCCIdentifier"/>
                <xs:element name="HKNCC" type="HongKongBankIdentifier"/>
                <xs:element name="AUBSBx" type="ExtensiveBranchNetworkIdentifier"/>
                <xs:element name="AUBSBs" type="SmallNetworkIdentifier"/>
            </xs:choice>
        </xs:sequence>
    </xs:complexType>
    <xs:simpleType name="CountryCode">
        <xs:restriction base="xs:string">
            <xs:pattern value="[A-Z]{2,2}"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:complexType name="Document">
        <xs:sequence>
            <xs:element name="GetLmt" type="GetLimitV04"/>
        </xs:sequence>
    </xs:complexType>
    <xs:simpleType name="ExtensiveBranchNetworkIdentifier">
        <xs:restriction base="xs:string">
            <xs:pattern value="AU[0-9]{6,6}"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="FedwireRoutingNumberIdentifier">
        <xs:restriction base="xs:string">
            <xs:pattern value="FW[0-9]{9,9}"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="GermanBankleitzahlIdentifier">
        <xs:restriction base="xs:string">
            <xs:pattern value="BL[0-9]{8,8}"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:complexType name="GetLimitV04">
        <xs:sequence>
            <xs:element name="MsgId" type="MessageIdentification"/>
            <xs:element maxOccurs="1" minOccurs="0" name="LmtQryDef" type="LimitQueryDefinition3"/>
        </xs:sequence>
    </xs:complexType>
    <xs:simpleType name="HongKongBankIdentifier">
        <xs:restriction base="xs:string">
            <xs:pattern value="HK[0-9]{3,3}"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="IBANIdentifier">
        <xs:restriction base="xs:string">
            <xs:pattern value="[a-zA-Z]{2,2}[0-9]{2,2}[a-zA-Z0-9]{1,30}"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="IrishNSCIdentifier">
        <xs:restriction base="xs:string">
            <xs:pattern value="IE[0-9]{6,6}"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="ItalianDomesticIdentifier">
        <xs:restriction base="xs:string">
            <xs:pattern value="IT[0-9]{10,10}"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:complexType name="LimitCriteria2">
        <xs:sequence>
            <xs:element maxOccurs="1" minOccurs="0" name="NewQryNm" type="Max35Text"/>
            <xs:element maxOccurs="1" minOccurs="0" name="SchCrit" type="LimitSearchCriteria2"/>
            <xs:element maxOccurs="1" minOccurs="0" name="RtrCrit" type="LimitReturnCriteria"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="LimitCriteriaDefinition2Choice">
        <xs:sequence>
            <xs:choice>
                <xs:element name="QryNm" type="Max35Text"/>
                <xs:element name="NewCrit" type="LimitCriteria2"/>
            </xs:choice>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="LimitQueryDefinition3">
        <xs:sequence>
            <xs:element maxOccurs="1" minOccurs="0" name="QryTp" type="QueryType2Code"/>
            <xs:element maxOccurs="1" minOccurs="0" name="LmtCrit" type="LimitCriteriaDefinition2Choice"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="LimitReturnCriteria">
        <xs:sequence>
            <xs:element maxOccurs="1" minOccurs="0" name="StartDtTmInd" type="RequestedIndicator"/>
            <xs:element maxOccurs="1" minOccurs="0" name="StsInd" type="RequestedIndicator"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="LimitSearchCriteria2">
        <xs:sequence>
            <xs:element maxOccurs="1" minOccurs="0" name="SysId" type="SystemIdentificationChoice"/>
            <xs:element maxOccurs="unbounded" minOccurs="0" name="BilLmtCtrPtyId" type="MemberIdentificationChoice"/>
            <xs:element maxOccurs="unbounded" minOccurs="0" name="DfltLmtTp" type="LimitType2Code"/>
            <xs:element maxOccurs="unbounded" minOccurs="0" name="CurLmtTp" type="LimitType2Code"/>
            <xs:element maxOccurs="1" minOccurs="0" name="AcctOwnr" type="BICIdentifier"/>
            <xs:element maxOccurs="1" minOccurs="0" name="AcctId" type="AccountIdentification1Choice"/>
        </xs:sequence>
    </xs:complexType>
    <xs:simpleType name="LimitType2Code">
        <xs:restriction base="xs:string">
            <xs:enumeration value="MULT"/>
            <xs:enumeration value="BILI"/>
            <xs:enumeration value="MAND"/>
            <xs:enumeration value="DISC"/>
            <xs:enumeration value="NELI"/>
            <xs:enumeration value="INBI"/>
            <xs:enumeration value="GLBL"/>
            <xs:enumeration value="DIDB"/>
            <xs:enumeration value="SPLC"/>
            <xs:enumeration value="SPLF"/>
            <xs:enumeration value="TDLC"/>
            <xs:enumeration value="TDLF"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="Max35Text">
        <xs:restriction base="xs:string">
            <xs:minLength value="1"/>
            <xs:maxLength value="35"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:complexType name="MemberIdentificationChoice">
        <xs:sequence>
            <xs:choice>
                <xs:element name="BIC" type="BICIdentifier"/>
                <xs:element name="ClrSysMmbId" type="ClearingSystemMemberIdentificationChoice"/>
            </xs:choice>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="MessageIdentification">
        <xs:sequence>
            <xs:element name="Id" type="Max35Text"/>
        </xs:sequence>
    </xs:complexType>
    <xs:simpleType name="NewZealandNCCIdentifier">
        <xs:restriction base="xs:string">
            <xs:pattern value="NZ[0-9]{6,6}"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="PortugueseNCCIdentifier">
        <xs:restriction base="xs:string">
            <xs:pattern value="PT[0-9]{8,8}"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="QueryType2Code">
        <xs:restriction base="xs:string">
            <xs:enumeration value="ALLL"/>
            <xs:enumeration value="CHNG"/>
            <xs:enumeration value="MODF"/>
            <xs:enumeration value="DELD"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="RequestedIndicator">
        <xs:restriction base="xs:boolean"/>
    </xs:simpleType>
    <xs:simpleType name="RussianCentralBankIdentificationCodeIdentifier">
        <xs:restriction base="xs:string">
            <xs:pattern value="RU[0-9]{9,9}"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:complexType name="SimpleIdentificationInformation">
        <xs:sequence>
            <xs:element name="Id" type="Max35Text"/>
        </xs:sequence>
    </xs:complexType>
    <xs:simpleType name="SmallNetworkIdentifier">
        <xs:restriction base="xs:string">
            <xs:pattern value="AU[0-9]{6,6}"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="SouthAfricanNCCIdentifier">
        <xs:restriction base="xs:string">
            <xs:pattern value="ZA[0-9]{6,6}"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="SpanishDomesticInterbankingIdentifier">
        <xs:restriction base="xs:string">
            <xs:pattern value="ES[0-9]{8,9}"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="SwissBCIdentifier">
        <xs:restriction base="xs:string">
            <xs:pattern value="SW[0-9]{3,5}"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="SwissSICIdentifier">
        <xs:restriction base="xs:string">
            <xs:pattern value="SW[0-9]{6,6}"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:complexType name="SystemIdentificationChoice">
        <xs:sequence>
            <xs:choice>
                <xs:element name="ClrSysId" type="CashClearingSystem1Code"/>
                <xs:element name="Ctry" type="CountryCode"/>
            </xs:choice>
        </xs:sequence>
    </xs:complexType>
    <xs:simpleType name="UKDomesticSortCodeIdentifier">
        <xs:restriction base="xs:string">
            <xs:pattern value="SC[0-9]{6,6}"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="UPICIdentifier">
        <xs:restriction base="xs:string">
            <xs:pattern value="[0-9]{8,17}"/>
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== luboid/leontestbed/bc2/sample/XML格式报文示例/nets.350.001.01.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--Sample XML file generated by XMLSpy v2009 sp1 (http://www.altova.com)-->
<Document xsi:schemaLocation="urn:swift:xsd:camt.009.001.04 camt.009.001.04.xsd" xmlns="urn:swift:xsd:camt.009.001.04" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<GetLmt>
		<MsgId>
		  <Id>2010090912345666</Id>
		</MsgId>
		<LmtQryDef>
			<LmtCrit>
				<NewCrit>
					<SchCrit>
					   <AcctId>
					     <DmstAcct>
						     <Id>103100000018</Id>
						   </DmstAcct>
						 </AcctId>
					</SchCrit>
				</NewCrit>
			</LmtCrit>
		</LmtQryDef>
	</GetLmt>
</Document>
