=== luboid/leontestbed/bc2/sample/Schema/pbcs.608.001.01.xsd
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<xs:schema xmlns="urn:cnaps:std:pbcs:2010:tech:xsd:pbcs.608.001.01" xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="urn:cnaps:std:pbcs:2010:tech:xsd:pbcs.608.001.01" elementFormDefault="qualified">
	<xs:element name="Document" type="Document"/>
	<xs:complexType name="Document">
		<xs:sequence>
			<xs:element name="ChrgAndRtrList" type="ChrgAndRtrListV01"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="ChrgAndRtrListV01">
		<xs:sequence>
			<xs:element name="GrpHdr" type="GroupHeader1"/>
			<xs:element name="ChrgAndRtrListInf" type="ChargeAndReturnListInformation1"/>
		</xs:sequence>
	</xs:complexType>
		<xs:complexType name="ChargeAndReturnListInformation1">
		<xs:sequence>
			<xs:element name="ChrgTp" type="ChargeTypeCode1"/>
			<xs:element name="ChrgPtcpt" type="Max14Text"/>
			<xs:element name="ChrgMnth" type="Max6NumericText"/>
			<xs:element name="StartDt" type="ISODate"/>
			<xs:element name="EndDt" type="ISODate"/>
			<xs:element name="TtlAmt" type="ActiveCurrencyAndAmount" />
			<xs:element name="NbOfSys" type="Max8NumericText" />
			<xs:element name="ChrgInf" type="ChargeInformation1" minOccurs="1" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="ChargeInformation1">
		<xs:sequence>
			<xs:element name="ChrgSys" type="SystemCode1"/>
			<xs:element name="Amt" type="ActiveCurrencyAndAmount"/>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="GroupHeader1">
		<xs:sequence>
			<xs:element name="MsgId" type="Max35Text"/>
			<xs:element name="CreDtTm" type="ISODateTime"/>
			<xs:element name="InstgPty" type="InstgPty1"/>
			<xs:element name="InstdPty" type="InstdPty1"/>
			<xs:element name="SysCd" type="SystemCode1"/>
			
			<xs:element name="Rmk" type="Max256Text" minOccurs="0"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="InstgPty1">
		<xs:sequence>
			<xs:element name="InstgDrctPty" type="Max14Text"/>
			<xs:element name="InstgPty" type="Max14Text" />
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="InstdPty1">
		<xs:sequence>
			<xs:element name="InstdDrctPty" type="Max14Text"/>
			<xs:element name="InstdPty" type="Max14Text" />
		</xs:sequence>
	</xs:complexType>
	<xs:simpleType name="Max8NumericText">
		<xs:restriction base="xs:string">
			<xs:minLength value="1"/>
			<xs:maxLength value="8"/>
			<xs:pattern value="[0-9]{1,8}"/>
		</xs:restriction>
	</xs:simpleType>
		<xs:simpleType name="Max6NumericText">
		<xs:restriction base="xs:string">
			<xs:minLength value="1"/>
			<xs:maxLength value="6"/>
			<xs:pattern value="[0-9]{1,6}"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="Max10NumericText">
		<xs:restriction base="xs:string">
			<xs:minLength value="1"/>
			<xs:maxLength value="10"/>
			<xs:pattern value="[0-9]{1,10}"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="Max14Text">
		<xs:restriction base="xs:string">
			<xs:minLength value="1"/>
			<xs:maxLength value="14"/>
			
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="Max4Text">
		<xs:restriction base="xs:string">
			<xs:minLength value="1"/>
			<xs:maxLength value="4"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="Max5Text">
		<xs:restriction base="xs:string">
			<xs:minLength value="1"/>
			<xs:maxLength value="5"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="Max35Text">
		<xs:restriction base="xs:string">
			<xs:minLength value="1"/>
			<xs:maxLength value="35"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="Max60Text">
		<xs:restriction base="xs:string">
			<xs:minLength value="1"/>
			<xs:maxLength value="60"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="Max105Text">
		<xs:restriction base="xs:string">
			<xs:minLength value="1"/>
			<xs:maxLength value="105"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="Max256Text">
		<xs:restriction base="xs:string">
			<xs:minLength value="1"/>
			<xs:maxLength value="256"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="Max2048Text">
		<xs:restriction base="xs:string">
			<xs:minLength value="1"/>
			<xs:maxLength value="2048"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="ISODate">
		<xs:restriction base="xs:date"/>
	</xs:simpleType>
	<xs:simpleType name="ISODateTime">
		<xs:restriction base="xs:dateTime"/>
	</xs:simpleType>
	<xs:simpleType name="SystemCode1">
		<xs:restriction base="xs:string">
			<xs:enumeration value="SAPS"/>
			<xs:enumeration value="HVPS"/>
			<xs:enumeration value="BEPS"/>
			<xs:enumeration value="CCMS"/>
			<xs:enumeration value="PMIS"/>
			<xs:enumeration value="IBPS"/>
			<xs:enumeration value="NCIS"/>
			<xs:enumeration value="ECDS"/>
			<xs:enumeration value="FXPS"/>
			<xs:enumeration value="NETS"/>
			<xs:enumeration value="PBCS"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="ChargeTypeCode1">
		<xs:restriction base="xs:string">
			<xs:enumeration value="CT00"/>
			<xs:enumeration value="CT01"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:complexType name="OriginalGroupHeader1">
		<xs:sequence>
			<xs:element name="OrgnlMsgId" type="Max35Text"/>
			<xs:element name="OrgnlInstgPty" type="Max14Text"/>
			<xs:element name="OrgnlMsgTp" type="Max35Text"/>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="Partition1">
		<xs:sequence>
			<xs:element name="TtlNb" type="Max8NumericText"/>
			<xs:element name="StartNb" type="Max8NumericText"/>
			<xs:element name="EndNb" type="Max8NumericText"/>
		</xs:sequence>
	</xs:complexType>

<xs:simpleType name="ActiveCurrencyAndAmount_SimpleType">
<xs:restriction base="xs:decimal">
<xs:minInclusive value="0"/>
<xs:fractionDigits value="5"/>
<xs:totalDigits value="18"/>
</xs:restriction>
</xs:simpleType>
<xs:complexType name="ActiveCurrencyAndAmount">
<xs:simpleContent>
<xs:extension base="ActiveCurrencyAndAmount_SimpleType">
<xs:attribute name="Ccy" type="ActiveCurrencyCode" use="required"/>
</xs:extension>
</xs:simpleContent>
</xs:complexType>
<xs:simpleType name="ActiveCurrencyCode">
<xs:restriction base="xs:string">
<xs:pattern value="[A-Z]{3,3}"/>
</xs:restriction>
</xs:simpleType>
</xs:schema>

=== luboid/leontestbed/bc2/generated_test/cnaps2/sample/xml/pbcs.608.001.01.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--Sample XML file generated by XMLSpy v2009 sp1 (http://www.altova.com)-->
<Document xsi:schemaLocation="urn:cnaps:std:pbcs:2010:tech:xsd:pbcs.608.001.01 pbcs.608.001.01.xsd" xmlns="urn:cnaps:std:pbcs:2010:tech:xsd:pbcs.608.001.01" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<ChrgAndRtrList>
		<GrpHdr>
			<MsgId>2010090912345678</MsgId>
			<CreDtTm>2010-09-09T09:30:47</CreDtTm>
			<InstgPty>
				<InstgDrctPty>0000</InstgDrctPty>
				<InstgPty>0000</InstgPty>
			</InstgPty>
			<InstdPty>
				<InstdDrctPty>103100000018</InstdDrctPty>
				<InstdPty>103100000018</InstdPty>
			</InstdPty>
			<SysCd>PBCS</SysCd>
			<Rmk>a</Rmk>
		</GrpHdr>
		<ChrgAndRtrListInf>
			<ChrgTp>CT00</ChrgTp>
			<ChrgPtcpt>103100000018</ChrgPtcpt>
			<ChrgMnth>201008</ChrgMnth>
			<StartDt>2010-08-01</StartDt>
			<EndDt>2010-08-31</EndDt>
			<TtlAmt Ccy="CNY">1000.00</TtlAmt>
			<NbOfSys>1</NbOfSys>
			<ChrgInf>
				<ChrgSys>HVPS</ChrgSys>
				<Amt Ccy="CNY">1000.00</Amt>
			</ChrgInf>
		</ChrgAndRtrListInf>
	</ChrgAndRtrList>
</Document>
