=== luboid/leontestbed/bc2/sample/Schema/saps.732.001.01.xsd
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<xs:schema xmlns="urn:cnaps:std:saps:2010:tech:xsd:saps.732.001.01" xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="urn:cnaps:std:saps:2010:tech:xsd:saps.732.001.01" elementFormDefault="qualified">
	<xs:element name="Document" type="Document"/>
	<xs:complexType name="Document">
		<xs:sequence>
			<xs:element name="ACSABSSttlmDtlRspn" type="ACSABSSttlmDtlRspnV01"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="ACSABSSttlmDtlRspnV01">
		<xs:sequence>
			<xs:element name="GrpHdr" type="GroupHeader1"/>
			<xs:element name="Prttn" type="Partition1"/>
			<xs:element name="OrgnlGrpHdr" type="OriginalGroupHeader1"/>
			<xs:element name="NPCPrcInf" type="NPCProcessInformation1"/>
			<xs:element name="ACSABSSttlmDtlRspnInf" type="ACSABSSettlementDetailResponseInformation1"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="ACSABSSettlementDetailResponseInformation1">
		<xs:sequence>
			<xs:element name="ChckngDt" type="ISODate"/>
			<xs:element name="ChckngInf" type="CheckingInformation1" minOccurs="0"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="CheckingInformation1">
		<xs:sequence>
			
				<xs:element name="UnltrlList" type="UnltrlList1" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element name="RvslList" type="RvslList1" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element name="NetgList" type="NettingList1" minOccurs="0" maxOccurs="unbounded"/>
			
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="UnltrlList1">
		<xs:sequence>
			<xs:element name="MsgId" type="Max35Text"/>
			<xs:element name="BookgId" type="Max14Text"/>
			<xs:element name="DbtCdtId" type="CreditDebitCode1"/>
			<xs:element name="Amt" type="ActiveCurrencyAndAmount"/>
			<xs:element name="CtgyPurpCd" type="Max5Text"/>
			<xs:element name="RspnSts" type="Max4Text"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="RvslList1">
		<xs:sequence>
			<xs:element name="MsgId" type="Max35Text"/>
			<xs:element name="BookgId" type="Max14Text"/>
			<xs:element name="ErrDt" type="ISODate"/>
			<xs:element name="DbtCdtId" type="CreditDebitCode1"/>
			<xs:element name="Amt" type="ActiveCurrencyAndAmount"/>
			<xs:element name="PlusMnsTp" type="PlusMinusTypeCode1"/>
			<xs:element name="CtgyPurpCd" type="Max5Text"/>
			<xs:element name="RspnSts" type="Max4Text"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="NettingList1">
		<xs:sequence>
			<xs:element name="MsgId" type="Max35Text"/>
			<xs:element name="RspnSts" type="Max4Text"/>
			<xs:element name="CtgyPurpCd" type="Max5Text"/>
			<xs:element name="NetgRnd" type="Max10NumericText"/>
			<xs:element name="DbtrAmt" type="SummaryAmountText"/>
			<xs:element name="CdtrAmt" type="SummaryAmountText"/>
			<xs:element name="NbOfMmb" type="Max8NumericText"/>
			<xs:element name="BookgList" type="BookingList1" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="BookingList1">
		<xs:sequence>
			<xs:element name="BookgId" type="Max14Text"/>
			<xs:element name="DbtCdtId" type="CreditDebitCode1"/>
			<xs:element name="Amt" type="ActiveCurrencyAndAmount"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="GroupHeader1">
		<xs:sequence>
			<xs:element name="MsgId" type="Max35Text"/>
			<xs:element name="CreDtTm" type="ISODateTime"/>
			<xs:element name="InstgPty" type="InstgPty1"/>
			<xs:element name="InstdPty" type="InstdPty1"/>
			<xs:element name="SysCd" type="SystemCode1"/>
			<xs:element name="Rmk" type="Max256Text" minOccurs="0"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="InstgPty1">
		<xs:sequence>
			<xs:element name="InstgDrctPty" type="Max14Text"/>
			<xs:element name="InstgPty" type="Max14Text" />
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="InstdPty1">
		<xs:sequence>
			<xs:element name="InstdDrctPty" type="Max14Text"/>
			<xs:element name="InstdPty" type="Max14Text" />
		</xs:sequence>
	</xs:complexType>
	<xs:simpleType name="Max8NumericText">
		<xs:restriction base="xs:string">
			<xs:minLength value="1"/>
			<xs:maxLength value="8"/>
			<xs:pattern value="[0-9]{1,8}"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="Max10NumericText">
		<xs:restriction base="xs:string">
			<xs:minLength value="1"/>
			<xs:maxLength value="8"/>
			<xs:pattern value="[0-9]{1,8}"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="Max14Text">
		<xs:restriction base="xs:string">
			<xs:minLength value="1"/>
			<xs:maxLength value="14"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="Max16NumericText">
		<xs:restriction base="xs:string">
			<xs:minLength value="1"/>
			<xs:maxLength value="16"/>
			<xs:pattern value="[0-9]{1,16}"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="Max2Text">
		<xs:restriction base="xs:string">
			<xs:minLength value="1"/>
			<xs:maxLength value="2"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="Max4Text">
		<xs:restriction base="xs:string">
			<xs:minLength value="1"/>
			<xs:maxLength value="4"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="Max5Text">
		<xs:restriction base="xs:string">
			<xs:minLength value="1"/>
			<xs:maxLength value="5"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="Max8Text">
		<xs:restriction base="xs:string">
			<xs:minLength value="1"/>
			<xs:maxLength value="8"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="Max35Text">
		<xs:restriction base="xs:string">
			<xs:minLength value="1"/>
			<xs:maxLength value="35"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="Max60Text">
		<xs:restriction base="xs:string">
			<xs:minLength value="1"/>
			<xs:maxLength value="60"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="Max105Text">
		<xs:restriction base="xs:string">
			<xs:minLength value="1"/>
			<xs:maxLength value="105"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="Max256Text">
		<xs:restriction base="xs:string">
			<xs:minLength value="1"/>
			<xs:maxLength value="256"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="Max2048Text">
		<xs:restriction base="xs:string">
			<xs:minLength value="1"/>
			<xs:maxLength value="2048"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="ISODate">
		<xs:restriction base="xs:date"/>
	</xs:simpleType>
	<xs:simpleType name="ISODateTime">
		<xs:restriction base="xs:dateTime"/>
	</xs:simpleType>
	<xs:simpleType name="SystemCode1">
		<xs:restriction base="xs:string">
			<xs:enumeration value="SAPS"/>
			<xs:enumeration value="HVPS"/>
			<xs:enumeration value="BEPS"/>
			<xs:enumeration value="CCMS"/>
			<xs:enumeration value="PMIS"/>
			<xs:enumeration value="IBPS"/>
			<xs:enumeration value="NCIS"/>
			<xs:enumeration value="ECDS"/>
			<xs:enumeration value="FXPS"/>
			<xs:enumeration value="NETS"/>
			<xs:enumeration value="PBCS"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:complexType name="OriginalGroupHeader1">
		<xs:sequence>
			<xs:element name="OrgnlMsgId" type="Max35Text"/>
			<xs:element name="OrgnlInstgPty" type="Max14Text"/>
			<xs:element name="OrgnlMT" type="Max35Text"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="Partition1">
		<xs:sequence>
			<xs:element name="TtlNb" type="Max8NumericText"/>
			<xs:element name="StartNb" type="Max8NumericText"/>
			<xs:element name="EndNb" type="Max8NumericText"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="NPCProcessInformation1">
		<xs:sequence>
			<xs:element name="PrcSts" type="Max4Text"/>
			<xs:element name="PrcCd" type="Max8Text"/>
			<xs:element name="RjctInf" type="Max105Text" minOccurs="0"/>
			<xs:element name="NetgDt" type="ISODate" minOccurs="0"/>
			<xs:element name="NetgRnd" type="Max2Text" minOccurs="0"/>
			<xs:element name="SttlmDt" type="ISODate" minOccurs="0"/>
			<xs:element name="RcvTm" type="ISODateTime" minOccurs="0"/>
			<xs:element name="TrnsmtTm" type="ISODateTime" minOccurs="0"/>
		</xs:sequence>
	</xs:complexType>
		<xs:simpleType name="PlusMinusTypeCode1">
		<xs:restriction base="xs:string">
			<xs:enumeration value="PM00"/>
			<xs:enumeration value="PM01"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="SummaryAmountText">
		<xs:restriction base="xs:string">
			<xs:pattern value="[A-Z]{3,3}[+-]\d{1,20}\.\d{2,2}"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="CreditDebitCode1">
		<xs:restriction base="xs:string">
			<xs:enumeration value="CRDT"/>
			<xs:enumeration value="DBIT"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="ActiveCurrencyAndAmount_SimpleType">
		<xs:restriction base="xs:decimal">
			<xs:minInclusive value="0"/>
			<xs:fractionDigits value="5"/>
			<xs:totalDigits value="18"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:complexType name="ActiveCurrencyAndAmount">
		<xs:simpleContent>
			<xs:extension base="ActiveCurrencyAndAmount_SimpleType">
				<xs:attribute name="Ccy" type="ActiveCurrencyCode" use="required"/>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
	<xs:simpleType name="ActiveCurrencyCode">
		<xs:restriction base="xs:string">
			<xs:pattern value="[A-Z]{3,3}"/>
		</xs:restriction>
	</xs:simpleType>
</xs:schema>

=== luboid/leontestbed/bc2/generated_test/cnaps2/sample/xml/saps.732.001.01.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--Sample XML file generated by XMLSpy v2009 sp1 (http://www.altova.com)-->
<Document xsi:schemaLocation="urn:cnaps:std:saps:2010:tech:xsd:saps.732.001.01 saps.732.001.01.xsd" xmlns="urn:cnaps:std:saps:2010:tech:xsd:saps.732.001.01" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<ACSABSSttlmDtlRspn>
		<GrpHdr>
			<MsgId>2010090977623325</MsgId>
			<CreDtTm>2010-09-09T09:30:47</CreDtTm>
			<InstgPty>
				<InstgDrctPty>0000</InstgDrctPty>
				<InstgPty>0000</InstgPty>
			</InstgPty>
			<InstdPty>
				<InstdDrctPty>308581000106</InstdDrctPty>
				<InstdPty>308581000106</InstdPty>
			</InstdPty>
			<SysCd>SAPS</SysCd>
			<Rmk>a</Rmk>
		</GrpHdr>
		<Prttn>
			<TtlNb>1</TtlNb>
			<StartNb>1</StartNb>
			<EndNb>1</EndNb>
		</Prttn>
		<OrgnlGrpHdr>
			<OrgnlMsgId>2010090977627598</OrgnlMsgId>
			<OrgnlInstgPty>308581000106</OrgnlInstgPty>
			<OrgnlMT>saps.732.001.01</OrgnlMT>
		</OrgnlGrpHdr>
		<NPCPrcInf>
			<PrcSts>PR05</PrcSts>
			<PrcCd>CB1I0000</PrcCd>
		</NPCPrcInf>
		<ACSABSSttlmDtlRspnInf>
			<ChckngDt>2010-09-09</ChckngDt>
			<ChckngInf>
				<UnltrlList>
					<MsgId>2010090977623398</MsgId>
					<BookgId>907100011301</BookgId>
					<DbtCdtId>CRDT</DbtCdtId>
					<Amt Ccy="CNY">100.00</Amt>
					<CtgyPurpCd>04201</CtgyPurpCd>
					<RspnSts>PR04</RspnSts>
				</UnltrlList>
				<RvslList>
					<MsgId>2010090977623392</MsgId>
					<BookgId>a</BookgId>
					<ErrDt>2010-08-13</ErrDt>
					<DbtCdtId>CRDT</DbtCdtId>
					<Amt Ccy="CNY">100.00</Amt>
					<PlusMnsTp>PM00</PlusMnsTp>
					<CtgyPurpCd>04201</CtgyPurpCd>
					<RspnSts>PR04</RspnSts>
				</RvslList>
				<NetgList>
					<MsgId>2010090977623391</MsgId>
					<RspnSts>PR04</RspnSts>
					<CtgyPurpCd>04201</CtgyPurpCd>
					<NetgRnd>1</NetgRnd>
					<DbtrAmt>AAA+100.00</DbtrAmt>
					<CdtrAmt>AAA+100.00</CdtrAmt>
					<NbOfMmb>1</NbOfMmb>
					<BookgList>
						<BookgId>222222222222</BookgId>
						<DbtCdtId>CRDT</DbtCdtId>
						<Amt Ccy="AAA">100.00</Amt>
					</BookgList>
				</NetgList>	
			</ChckngInf>
		</ACSABSSttlmDtlRspnInf>
	</ACSABSSttlmDtlRspn>
</Document>
