=== luboid/leontestbed/bc2/sample/Schema/saps.734.001.01.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2009 sp1 (http://www.altova.com) by aps-lzy (EMBRACE) -->
<xs:schema xmlns="urn:cnaps:std:saps:2010:tech:xsd:saps.734.001.01" xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="urn:cnaps:std:saps:2010:tech:xsd:saps.734.001.01" elementFormDefault="qualified">
	<xs:element name="Document" type="Document"/>
	<xs:complexType name="Document">
		<xs:sequence>
			<xs:element name="ACSTCBSAnlAcctg" type="ACSTCBSAnlAcctgV1"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="ACSTCBSAnlAcctgV1">
		<xs:sequence>
			<xs:element name="GrpHdr" type="GroupHeader1"/>
			<xs:element name="ACSTCBSAnlAcctgInf" type="ACSTCBSAnnualAccountingInformation1"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="ACSTCBSAnnualAccountingInformation1">
		<xs:sequence>
			<xs:element name="Acct" type="Max16NumericText"/>
			<xs:element name="InitlAmt" type="SummaryAmountText"/>
			<xs:element name="AnlDbtrAmt" type="SummaryAmountText"/>
			<xs:element name="AnlCdtrAmt" type="SummaryAmountText"/>
			<xs:element name="FnlAmt" type="SummaryAmountText"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="GroupHeader1">
		<xs:sequence>
			<xs:element name="MsgId" type="Max35Text"/>
			<xs:element name="CreDtTm" type="ISODateTime"/>
			<xs:element name="InstgPty" type="InstgPty1"/>
			<xs:element name="InstdPty" type="InstdPty1"/>
			<xs:element name="SysCd" type="SystemCode1"/>
			<xs:element name="Rmk" type="Max256Text" minOccurs="0"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="InstgPty1">
		<xs:sequence>
			<xs:element name="InstgDrctPty" type="Max14Text"/>
			<xs:element name="InstgPty" type="Max14Text" />
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="InstdPty1">
		<xs:sequence>
			<xs:element name="InstdDrctPty" type="Max14Text"/>
			<xs:element name="InstdPty" type="Max14Text" />
		</xs:sequence>
	</xs:complexType>
	<xs:simpleType name="ISODate">
		<xs:restriction base="xs:date"/>
	</xs:simpleType>
	<xs:simpleType name="Max35Text">
		<xs:restriction base="xs:string">
			<xs:minLength value="1"/>
			<xs:maxLength value="35"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="Max105Text">
		<xs:restriction base="xs:string">
			<xs:minLength value="1"/>
			<xs:maxLength value="105"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="Max4Text">
		<xs:restriction base="xs:string">
			<xs:minLength value="1"/>
			<xs:maxLength value="4"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="ISODateTime">
		<xs:restriction base="xs:dateTime"/>
	</xs:simpleType>
	<xs:simpleType name="Max14Text">
		<xs:restriction base="xs:string">
			<xs:minLength value="1"/>
			<xs:maxLength value="14"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="Max16NumericText">
		<xs:restriction base="xs:string">
			<xs:minLength value="1"/>
			<xs:maxLength value="16"/>
			<xs:pattern value="[0-9]{1,16}"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="SystemCode1">
		<xs:restriction base="xs:string">
			<xs:enumeration value="SAPS"/>
			<xs:enumeration value="HVPS"/>
			<xs:enumeration value="BEPS"/>
			<xs:enumeration value="CCMS"/>
			<xs:enumeration value="PMIS"/>
			<xs:enumeration value="IBPS"/>
			<xs:enumeration value="NCIS"/>
			<xs:enumeration value="ECDS"/>
			<xs:enumeration value="FXPS"/>
			<xs:enumeration value="NETS"/>
			<xs:enumeration value="PBCS"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="Max2048Text">
		<xs:restriction base="xs:string">
			<xs:minLength value="1"/>
			<xs:maxLength value="2048"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="Max256Text">
		<xs:restriction base="xs:string">
			<xs:minLength value="1"/>
			<xs:maxLength value="256"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:complexType name="ResponseInformation1">
		<xs:sequence>
			<xs:element name="Sts" type="Max4Text"/>
			<xs:element name="RjctCd" type="Max4Text" minOccurs="0"/>
			<xs:element name="RjctInf" type="Max105Text" minOccurs="0"/>
			<xs:element name="PrcPty" type="Max14Text" minOccurs="0"/>
		</xs:sequence>
	</xs:complexType>
	<xs:simpleType name="SummaryAmountText">
		<xs:restriction base="xs:string">
			<xs:pattern value="[A-Z]{3,3}[+-]\d{1,20}\.\d{2,2}"/>
		</xs:restriction>
	</xs:simpleType>
</xs:schema>

=== luboid/leontestbed/bc2/generated_test/cnaps2/sample/xml/saps.734.001.01__.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--Sample XML file generated by XMLSpy v2009 sp1 (http://www.altova.com)-->
<Document xsi:schemaLocation="urn:cnaps:std:saps:2010:tech:xsd:saps.734.001.01 saps.734.001.01.xsd" xmlns="urn:cnaps:std:saps:2010:tech:xsd:saps.734.001.01" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<ACSTCBSAnlAcctg>
		<GrpHdr>
			<MsgId>2010090912555591</MsgId>
			<CreDtTm>2010-09-09T09:30:47</CreDtTm>
			<InstgPty>
				<InstgDrctPty>0000</InstgDrctPty>
				<InstgPty>0000</InstgPty>
			</InstgPty>
			<InstdPty>
				<InstdDrctPty>308581000106</InstdDrctPty>
				<InstdPty>308581000106</InstdPty>
			</InstdPty>
			<SysCd>SAPS</SysCd>
			<Rmk>a</Rmk>
		</GrpHdr>
		<ACSTCBSAnlAcctgInf>
			<Acct>1234308581000106</Acct>
			<InitlAmt>1000.00</InitlAmt>
			<AnlDbtrAmt>1000.00</AnlDbtrAmt>
			<AnlCdtrAmt>1000.00</AnlCdtrAmt>
			<FnlAmt>1000.00</FnlAmt>
		</ACSTCBSAnlAcctgInf>
	</ACSTCBSAnlAcctg>
</Document>
